2020-10-20 09:38:27 [twisted] CRITICAL: Unhandled error in Deferred:
2020-10-20 09:38:27 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/home/zhang/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/zhang/.pyenv/versions/3.6.8/lib/python3.6/site-packages/scrapy/crawler.py", line 87, in crawl
    self.engine = self._create_engine()
  File "/home/zhang/.pyenv/versions/3.6.8/lib/python3.6/site-packages/scrapy/crawler.py", line 101, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/home/zhang/.pyenv/versions/3.6.8/lib/python3.6/site-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/home/zhang/.pyenv/versions/3.6.8/lib/python3.6/site-packages/scrapy/core/scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/home/zhang/.pyenv/versions/3.6.8/lib/python3.6/site-packages/scrapy/middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/zhang/.pyenv/versions/3.6.8/lib/python3.6/site-packages/scrapy/middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "/home/zhang/.pyenv/versions/3.6.8/lib/python3.6/site-packages/scrapy/utils/misc.py", line 51, in load_object
    mod = import_module(module)
  File "/home/zhang/.pyenv/versions/3.6.8/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zhang/Workspace/python_crawl/DoiDown/DoiDown/pipelines.py", line 12, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
